version: '2'
services:
  postgres:
    extends:
      file: postgresql.yml
      service: postgresql
    container_name: postgresql
  redis:
    extends:
      file: redis.yml
      service: redis
    container_name: redis
